version: 0.2

env:
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  parameter-store:
    SSH_PRIV_KEY: "AMIBuild-Key"

phases:
  pre_build:
    commands:
      - echo Running sanity checks...
      - ansible --version
  build:
    commands:
      - echo Build started on `date`
      - mkdir ~/.ssh && chmod 700 ~/.ssh && echo "-----BEGIN RSA PRIVATE KEY-----" > ~/.ssh/key.pem && echo $SSH_PRIV_KEY | tr ' ' '\n' | tail -n +5 | head -n -4 >> ~/.ssh/key.pem && echo "-----END RSA PRIVATE KEY-----" >> ~/.ssh/key.pem && chmod 600 ~/.ssh/key.pem
      - cd ansible && python creds.py && ansible-galaxy install -r requirements.yml -p roles && ansible-playbook -i inventory.ini --private-key=~/.ssh/key.pem playbook.yml
