version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing pre-requisites
      - apt-get update -y && apt-get install -y ansible python-boto
      - echo Running sanity checks...
      - env
      - ansible --version
  build:
    commands:
      - echo Build started on `date`
      - ansible-galaxy install -r requirements.yml -p roles
      - ansible-playbook -i 'localhost,' playbook.yml
