version: 0.2

phases:
  pre_build:
    commands:
      - echo Running sanity checks...
      - ansible --version
  build:
    commands:
      - echo Build started on `date`
      - cd ansible && export SSH_PRIV_KEY && python creds.py && ansible-galaxy install -r requirements.yml -p roles && ansible-playbook -vvvv -i inventory.ini --private-key=key.pem -e 'host_key_checking=False' playbook.yml
