version: 0.2

phases:
  pre_build:
    commands:
      - echo Running sanity checks...
      - env
      - ansible --version
      - curl http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
  build:
    commands:
      - echo Build started on `date`
      - cd ansible && ansible-galaxy install -r requirements.yml -p roles && ansible-playbook -i 'localhost,' playbook.yml
