version: 0.2

phases:
  pre_build:
    commands:
      - echo Running sanity checks...
      - env
      - ansible --version
  build:
    commands:
      - echo Build started on `date`
      - cd ansible && python creds.py && ansible-galaxy install -r requirements.yml -p roles && ansible-playbook -i inventory.ini playbook.yml
