version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing pre-requisites
      - pip install virtualenv
      - virtualenv /var/tmp/foo
      - source /var/tmp/foo/bin/activate
      - pip install ansible boto
      - echo Running sanity checks...
      - env
      - ansible --version
  build:
    commands:
      - echo Build started on `date`
      - ansible-galaxy install -r requirements.yml -p roles
      - ansible-playbook -i 'localhost,' playbook.yml
